2020-03-04 12:48:41,872 ERROR: Exception on /news_sites [GET] [in /Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/routes.py", line 182, in news_sites
    return render_template("news_sites.html", title='News', story_news = nice_dict, categories_new = categories)
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/templates/news_sites.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/templates/base.html", line 49, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/templates/news_sites.html", line 27, in block "app_content"
    {% include '_news.html' %}
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/templates/_news.html", line 5, in template
    <a href="{{ url_for('category', category=category) }}">{{category}}>
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2020-03-04 12:48:43,728 ERROR: Exception on /news_sites [GET] [in /Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/routes.py", line 182, in news_sites
    return render_template("news_sites.html", title='News', story_news = nice_dict, categories_new = categories)
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/templates/news_sites.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/templates/base.html", line 49, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/templates/news_sites.html", line 27, in block "app_content"
    {% include '_news.html' %}
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/alfredtingey/news-aggregation-system/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/alfredtingey/news-aggregation-system/news_agg_app/app/templates/_news.html", line 5, in template
    <a href="{{ url_for('category', category=category) }}">{{category}}>
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2020-03-04 12:50:44,259 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system/news_agg_app/app/__init__.py:49]
2020-03-04 12:51:11,125 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system/news_agg_app/app/__init__.py:49]
2020-03-04 12:51:36,810 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system/news_agg_app/app/__init__.py:49]
2020-03-04 12:53:38,044 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system/news_agg_app/app/__init__.py:49]
2020-03-04 12:59:18,970 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system/news_agg_app/app/__init__.py:49]
2020-03-05 00:35:24,855 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system/news_agg_app/app/__init__.py:49]
2020-03-26 13:31:50,638 INFO: Microblog startup [in /Users/alfredtingey/news-aggregation-system/news_agg_app/app/__init__.py:49]
